FROM registry.redhat.io/dotnet/dotnet-21-rhel7 AS base
WORKDIR /app
COPY ["WebApplication3.vbproj", "./"]
RUN dotnet restore "./WebApplication3.vbproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "WebApplication3.vbproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "WebApplication3.vbproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
COPY . ./
ENTRYPOINT ["dotnet", "WebApplication3.dll"]